{
    'name': 'Construction ERP - NEMAL',
    'version': '1.0',
    'category': 'Construction',
    'summary': 'Core construction management: Projects, Real Estate Units, Daily Logs',
    'description': """
        Construction & Real Estate ERP
        ==============================
        Phase 1 Modules:
        - Extended Projects
        - Real Estate Unit Tracking
        - Daily Progress Logs
    """,
    'author': 'Your Company',
    'depends': ['base', 'project', 'analytic', 'account', 'stock', 'purchase', 'sale', 'portal'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/ir_sequence_data.xml',
        'data/mail_templates.xml',
        'views/product_template_views.xml',
        'views/partner_views.xml',
        'views/menu_views.xml',
        'views/estimate_views.xml',
        'views/document_views.xml',
        'views/construction_scrap_views.xml',
        'views/consumption_views.xml',
        'views/daily_log_views.xml',
        'views/real_estate_unit_views.xml',
        'views/construction_phase_views.xml',
        'views/construction_lifecycle_views.xml',
        'views/construction_compliance_views.xml',
        'views/inspection_views.xml',
        'views/cost_sheet_views.xml',
        'views/cpr_views.xml',
        'views/job_order_views.xml',
        'views/usage_log_views.xml',
        'views/variation_views.xml',
        'views/hse_quality_views.xml',
        'views/engineering_control_views.xml',
        'views/job_order_portal_templates.xml',
        'views/installment_views.xml',
        'views/project_views.xml',
        'views/dashboard_views.xml',
        'views/res_config_settings_views.xml',
        'views/material_requisition_views.xml',
        'views/portal_templates.xml',
        'views/portal_contractor_templates.xml',
        'views/sale_views.xml',
        'views/purchase_views.xml',
        'views/account_move_views.xml',
        'views/traceability_views.xml',
        'wizard/project_report_wizard_views.xml',
        'wizard/material_confirmation_wizard_view.xml',
        'wizard/construction_purchase_wizard_view.xml',
        'report/project_reports.xml',
        'report/project_report_templates.xml',
    ],
    "images": [
        "static/description/banner.png",
    ],
    'assets': {
        'web.assets_backend': [
            'construction_erp/static/src/css/dashboard.css',
            'construction_erp/static/src/css/kanban.css',
            'construction_erp/static/src/css/profitability_dashboard.css',
            'construction_erp/static/src/js/dashboard.js',
            'construction_erp/static/src/js/profitability_dashboard.js',
            'construction_erp/static/src/xml/dashboard_templates.xml',
            'construction_erp/static/src/xml/profitability_dashboard_templates.xml',
            'construction_erp/static/src/js/image_gallery_widget.js',
            'construction_erp/static/src/xml/image_gallery_widget.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
