# -*- coding: utf-8 -*-
from . import notification_mixin
from . import project_project
from . import real_estate_unit
from . import daily_log
from . import res_partner
from . import account_move
from . import construction_estimate
from . import inspection
from . import job_order
from . import material_requisition
from . import installment_plan
from . import project_document
from . import project_image
from . import consumption
from . import construction_scrap
from . import construction_phase
from . import construction_compliance
from . import product_template
from . import construction_dashboard
from . import res_config_settings
from . import sale_order
from . import traceability
from . import project_phase_config
from . import purchase_order
from . import cost_sheet
from . import cpr
from . import variation_order
from . import safety_incident
from . import permit_to_work
from . import construction_ncr
from . import construction_rfi
from . import construction_submittal
from . import construction_usage
